name: 'stagexl_contrast_bug'
version: 0.0.1
description: A sample of a possible StageXL bug with the adjustContrast method.
#author: RobertMcdermot robert.mcdermot@gmail.com
#homepage: https://www.robertmcdermot.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  stagexl: "^0.13.10+2"

transformers:
- dart_to_js_script_rewriter
